### ISSUE TITLE
Error: cannot import name plugin

### ISSUE THREAD

**Issue by Ved2302** [nexhero/wolframalpha_jasper#5]
I copied Knowledged.py in clients/modules directory. I also installed wolframalpha module. However on running jasper, following error is shown:

`WARNING:client.brain:Skipped module 'Knowledged' due to an error.
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 43, in get_modules
    mod = loader.load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/home/pi/jasper/client/modules/Knowledged.py", line 8, in <module>
    from jasper import plugin
`
How to solve this? Thank you! :)

**Comment by buzink** [comment]
I get the same error.

**Comment by DarthToker** [comment]
Same here

**Comment by DarthToker** [comment]
Ok I think we need to git the developers branch and not the main branch. It seems to be structured different then the main. Will download and when I get home.

**Comment by DarthToker** [comment]
The jasper development branch I mean

**Comment by nefutpowers** [comment]
Just get the knowledged.py commit on Apr 18, 2015, and you'd get the working version.

**Comment by ghost** [comment]
well how can we get that commit ? I'm new to github. Can anyone please help .
Many Thanks :)
